### ISSUE TITLE
Blur out background for landing popup

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#1063]
> To blur out the background, perhaps we can add `id` to the modal content:

```r
  showModal(
    modalDialog(
      id = "landingpopup", ## adding ID
      title = title,
      content,
      footer = buttons
    )
  )
```

Then, we update `custom.css` file and use the `:has` pseudo-class:
```css
#shiny-modal:has(> .modal-dialog > .modal-content > #landingpopup) {
  backdrop-filter: blur(10px);
}
```

_Originally posted by @donyunardi in https://github.com/insightsengineering/teal.modules.general/issues/585#issuecomment-1763732723_

We decided to close the tmg PR and move the `landing_popup_module` to teal.
I think we forgot to add the css part to blur out the background during the changes.

![image](https://github.com/insightsengineering/teal/assets/8597300/e582e9d6-8761-453c-b117-c23070977015)
