### ISSUE TITLE
Add bookmarking information to vignettes

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal#1185]
1. Add new vignette that explains bookmarking. 
- explain that `teal` bookmarks `teal` and modules bookmark themselves
- explain the `teal_bookmarkable` attribute of modules
- use [this issue](https://github.com/insightsengineering/coredev-tasks/issues/520) and [this PR](https://github.com/insightsengineering/teal/pull/1011) as sources of content

2. Amend `Creating Custom Modules` vignette.
- mention bookmarking requirements and attribute
- link to bookmarking vignette

3. Amend `pkgdown`.
suggested:
```
- title: Extending `teal`
  navbar: Extending `teal`
  contents:
    - creating-custom-modules
    - bookmarking-teal-applications
    - adding-support-for-reporting
```
