### ISSUE TITLE
fix filtered_data_set_filters

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/teal#42]
Previous implementation of `filtered_data_set_filters` required named list of filters 
```yaml
- ADSL
  - SEX: [M, F]
  - AGE: default_filter
ADTTE
  - PARAMCD: [OS, PFS]
```
Now situation is different because of MAE we need to point filters to the relevant FilterQueue and  ReactiveQueue. So that:
```yaml
- ADSL # dataset name
  - filter # FilterQueue name
    - [[1]] # ReactiveQueue index
      - SEX: [M, F]
      - AGE: [20, 65]

MAE # dataset name
  - patient # FilterQueue name
    - y # ReactiveQueue index
      - SEX: [M, F]
      - AGE: [20, 65]
   - <experiment_name>  # FilterQueue name
     - subset # ReactiveQueue index
       - SIZE: [8, 205012]
     - select # ReactiveQueue index
       - TUMOR_TYPE: [primary]
```

Please implement also `default_filter()` to not force specification of the filter 

Above is necessary to enable bookmarking

Provenance: 
```
Creator: gogonzo
```
